spring.application.name=perfulandia

# Rutas y Puerto del Servidor
server.servlet.context-path=/api
server.port=8000

# Configuración de Swagger/OpenAPI
# Habilita Swagger UI
springdoc.swagger-ui.enabled=true
# Establece la ruta para acceder a la interfaz de usuario de Swagger
springdoc.swagger-ui.path=/swagger-ui.html
# Establece la ruta donde estará el archivo OpenAPI (YAML/JSON)
springdoc.api-docs.path=/v3/api-docs

# H2 in-memory
spring.datasource.url=jdbc:h2:mem:perfulandia;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#JWT
app.security.jwt.secret=UnaClaveSecretaMuyLargaDeMasDe32CaracteresParaFirmarTokens

# 2. Tiempo de expiración en milisegundos (la que te falta ahora)
app.security.jwt.expiration-ms=86400000